title: "GrupoA.github.io"
description: "Proyecto de TDD"
url: "https://WilderAndr.github.io"
baseurl: "/PA3TDD"

markdown: kramdown
theme: jekyll-theme-cayman

repository: "WilderAndr/GrupoA.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

highlighter: rouge
permalink: pretty

assets:
  sources:
    - assets
  cache: false

include:
  - assets/js
  - assets/js/tests
  - assets/css
  - _data/db.json

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .vscode
  - .github

development: &development
  url: http://localhost:4000
  assets:
    debug: true

production: &production
  url: https://WilderAndr.github.io
  assets:
    debug: false

environments:
  development: *development
  production: *production

test_env: &test_env
  url: ""
  baseurl: ""

custom:
  orm:
    debug: true
    base_url: ""

github:
  repository: WilderAndr/GrupoA.github.io
  branch: main

seo:
  title: true
  description: true
  image: "/assets/images/og-image.jpg"
